Scro pre vote branch
iofoundry/ontology pull request #44
Opened 2023-02-09 16:21 UTC by wsobel

* Pre Release Version of SCRO for review.
*  Vote has passed, now merging into master

2023-02-20 08:56 UTC, mereolog requested changes
There is a couple of ill-formed axioms/definition: [iof_supplychain_illformed_axioms_faae427.xlsx](https://github.com/iofoundry/ontology/files/10782367/iof_supplychain_illformed_axioms_faae427.xlsx)
See also https://github.com/iofoundry/ontology/issues/46#issuecomment-1434757440.

2023-02-20 08:56 UTC, mereolog commented on supplychain/SupplyChainReferenceOntology.rdf
> +		<dcterms:contributor xml:lang="en-us">Boonserm Kulvatanyou, NIST</dcterms:contributor>
I think that https://oagiscore.atlassian.net/wiki/spaces/IOF/pages/4532142081/IOF+Annotation+Property+Guide+V2.2#Summary-of-Annotation-Requirements requires 'en-US'.

This issue should have been found by the hygiene tests, but it was not.
https://github.com/iofoundry/ontology/pull/47 should fix this bug in hygiene tests.

2023-03-15 17:23 UTC, mereolog approved these changes

2023-03-16 02:09 UTC, ElisaKendall approved these changes
I'll approve this but I thought we were renaming the ontology from SupplyChainReferenceOntology to SupplyChain?

Otherwise, really great job on eliminating all the hygiene issues!

2023-03-17 02:59 UTC, fameri commented
> I'll approve this but I thought we were renaming the ontology from SupplyChainReferenceOntology to SupplyChain?
> 
> Otherwise, really great job on eliminating all the hygiene issues!

I renamed SupplyChainReferenceOntology.rdf to SupplyChain.rdf (and updated the IRIs) in the branch. Should I submit another pull request? 
Farhad

2023-03-17 07:48 UTC, mereolog requested changes
@fameri after the rename of the ontology you need to update all references to the previous file name and the previous IRI in the catalog and metadata files. 

I can do it for you if you want.

2023-03-17 14:07 UTC, MilosDrobnjakovic approved these changes

2023-03-17 14:18 UTC, mereolog commented
> > @fameri after the rename of the ontology you need to update all references to the previous file name and the previous IRI in the catalog and metadata files.
> > I can do it for you if you want.
> 
> @mereolog I actually updated the IRIs as well. Can you please check and pull?

There are still 7 references to [SupplyChainReferenceOntology](https://spec.industrialontologies.org/ontology/supplychain/SupplyChainReferenceOntology/) - see below.

![image](https://user-images.githubusercontent.com/11171688/225930192-077a0676-08e9-4de6-bbe8-c873658948c9.png)

We need to rename at least those in catalog and metadata files.

2023-03-20 07:21 UTC, mereolog requested changes
There are still two references to SupplyChainReferenceOntology in https://github.com/iofoundry/ontology/blob/bdcbcd066ff6d20f530e75ce7188ec9dd9bb7436/supplychain/Metadatasupplychain.rdf.

2023-03-21 06:30 UTC, mereolog approved these changes

2023-03-21 06:30 UTC, merged