Action JIRA edits 2/10
iofoundry/ontology pull request #75
Opened 2023-10-02 03:37 UTC by Caitlin2694

2023-10-02 06:44 UTC, mhodki approved these changes

2023-10-02 06:46 UTC, mhodki approved these changes

2023-10-02 06:56 UTC, mhodki approved these changes

2023-10-02 13:20 UTC, MilosDrobnjakovic reviewed
The changes look good except line 245 (failure process), you changed to 'is primitive' true. Which is not the case as we just changed the NL (axiomatically the class is the same)
P.S. I do not see the change here, so please take a look at 'qualification specification' and check that the IRI and label is matching (I assume based on your decline that you want 'qualification spec' and not 'person qualification spec' so change the label accordingly)

2023-10-02 13:38 UTC, MilosDrobnjakovic requested changes
I have added the requested changes in the previous comment

2023-10-04 00:36 UTC, mhodki approved these changes

2023-10-04 00:36 UTC, mhodki commented
@MilosDrobnjakovic  thanks for the suggestions, they have all been actioned. Please can you review.

2023-10-04 12:46 UTC, MilosDrobnjakovic approved these changes

2023-10-16 01:29 UTC, merged